import type { Metadata } from "next";
// import Head from "next/head";
// import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
// import { link } from "fs";

const font = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Alwi's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className={font.className}>
          <Navbar />
          {children}
        </div>
  );
}
